/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReminderId = IDL.Nat;
export const ReminderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'status' : ReminderStatus,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'scheduledAt' : Timestamp,
});
export const CreateReminderInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'scheduledAt' : Timestamp,
});
export const UpdateReminderInput = IDL.Record({
  'id' : ReminderId,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'scheduledAt' : Timestamp,
});

export const idlService = IDL.Service({
  'completeReminder' : IDL.Func([ReminderId], [IDL.Opt(Reminder)], []),
  'createReminder' : IDL.Func([CreateReminderInput], [Reminder], []),
  'deleteReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
  'dismissReminder' : IDL.Func([ReminderId], [IDL.Opt(Reminder)], []),
  'getReminder' : IDL.Func([ReminderId], [IDL.Opt(Reminder)], ['query']),
  'listReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'updateReminder' : IDL.Func([UpdateReminderInput], [IDL.Opt(Reminder)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReminderId = IDL.Nat;
  const ReminderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'status' : ReminderStatus,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'scheduledAt' : Timestamp,
  });
  const CreateReminderInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'scheduledAt' : Timestamp,
  });
  const UpdateReminderInput = IDL.Record({
    'id' : ReminderId,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'scheduledAt' : Timestamp,
  });
  
  return IDL.Service({
    'completeReminder' : IDL.Func([ReminderId], [IDL.Opt(Reminder)], []),
    'createReminder' : IDL.Func([CreateReminderInput], [Reminder], []),
    'deleteReminder' : IDL.Func([ReminderId], [IDL.Bool], []),
    'dismissReminder' : IDL.Func([ReminderId], [IDL.Opt(Reminder)], []),
    'getReminder' : IDL.Func([ReminderId], [IDL.Opt(Reminder)], ['query']),
    'listReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'updateReminder' : IDL.Func([UpdateReminderInput], [IDL.Opt(Reminder)], []),
  });
};

export const init = ({ IDL }) => { return []; };