/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateReminderInput {
  'title' : string,
  'subject' : string,
  'notes' : [] | [string],
  'scheduledAt' : Timestamp,
}
export interface Reminder {
  'id' : ReminderId,
  'status' : ReminderStatus,
  'title' : string,
  'subject' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'scheduledAt' : Timestamp,
}
export type ReminderId = bigint;
export type ReminderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'dismissed' : null };
export type Timestamp = bigint;
export interface UpdateReminderInput {
  'id' : ReminderId,
  'title' : string,
  'subject' : string,
  'notes' : [] | [string],
  'scheduledAt' : Timestamp,
}
export type UserId = Principal;
export interface _SERVICE {
  'completeReminder' : ActorMethod<[ReminderId], [] | [Reminder]>,
  'createReminder' : ActorMethod<[CreateReminderInput], Reminder>,
  'deleteReminder' : ActorMethod<[ReminderId], boolean>,
  'dismissReminder' : ActorMethod<[ReminderId], [] | [Reminder]>,
  'getReminder' : ActorMethod<[ReminderId], [] | [Reminder]>,
  'listReminders' : ActorMethod<[], Array<Reminder>>,
  'updateReminder' : ActorMethod<[UpdateReminderInput], [] | [Reminder]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];