/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export type ReminderId = bigint;
export interface Reminder {
    id: ReminderId;
    status: ReminderStatus;
    title: string;
    subject: string;
    owner: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes?: string;
    scheduledAt: Timestamp;
}
export interface UpdateReminderInput {
    id: ReminderId;
    title: string;
    subject: string;
    notes?: string;
    scheduledAt: Timestamp;
}
export interface CreateReminderInput {
    title: string;
    subject: string;
    notes?: string;
    scheduledAt: Timestamp;
}
export enum ReminderStatus {
    pending = "pending",
    completed = "completed",
    dismissed = "dismissed"
}
export interface backendInterface {
    completeReminder(id: ReminderId): Promise<Reminder | null>;
    createReminder(input: CreateReminderInput): Promise<Reminder>;
    deleteReminder(id: ReminderId): Promise<boolean>;
    dismissReminder(id: ReminderId): Promise<Reminder | null>;
    getReminder(id: ReminderId): Promise<Reminder | null>;
    listReminders(): Promise<Array<Reminder>>;
    updateReminder(input: UpdateReminderInput): Promise<Reminder | null>;
}
import type { CreateReminderInput as _CreateReminderInput, Reminder as _Reminder, ReminderId as _ReminderId, ReminderStatus as _ReminderStatus, Timestamp as _Timestamp, UpdateReminderInput as _UpdateReminderInput, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeReminder(arg0: ReminderId): Promise<Reminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.completeReminder(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeReminder(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReminder(arg0: CreateReminderInput): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(to_candid_CreateReminderInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Reminder_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(to_candid_CreateReminderInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Reminder_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReminder(arg0: ReminderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async dismissReminder(arg0: ReminderId): Promise<Reminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissReminder(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissReminder(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminder(arg0: ReminderId): Promise<Reminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminder(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminder(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReminders();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReminders();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReminder(arg0: UpdateReminderInput): Promise<Reminder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(to_candid_UpdateReminderInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(to_candid_UpdateReminderInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ReminderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderStatus): ReminderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Reminder_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reminder): Reminder {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Reminder]): Reminder | null {
    return value.length === 0 ? null : from_candid_Reminder_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReminderId;
    status: _ReminderStatus;
    title: string;
    subject: string;
    owner: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    notes: [] | [string];
    scheduledAt: _Timestamp;
}): {
    id: ReminderId;
    status: ReminderStatus;
    title: string;
    subject: string;
    owner: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    notes?: string;
    scheduledAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ReminderStatus_n4(_uploadFile, _downloadFile, value.status),
        title: value.title,
        subject: value.subject,
        owner: value.owner,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.notes)),
        scheduledAt: value.scheduledAt
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    dismissed: null;
}): ReminderStatus {
    return "pending" in value ? ReminderStatus.pending : "completed" in value ? ReminderStatus.completed : "dismissed" in value ? ReminderStatus.dismissed : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reminder>): Array<Reminder> {
    return value.map((x)=>from_candid_Reminder_n2(_uploadFile, _downloadFile, x));
}
function to_candid_CreateReminderInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateReminderInput): _CreateReminderInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateReminderInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateReminderInput): _UpdateReminderInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ReminderId;
    title: string;
    subject: string;
    notes?: string;
    scheduledAt: Timestamp;
}): {
    id: _ReminderId;
    title: string;
    subject: string;
    notes: [] | [string];
    scheduledAt: _Timestamp;
} {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        scheduledAt: value.scheduledAt
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subject: string;
    notes?: string;
    scheduledAt: Timestamp;
}): {
    title: string;
    subject: string;
    notes: [] | [string];
    scheduledAt: _Timestamp;
} {
    return {
        title: value.title,
        subject: value.subject,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        scheduledAt: value.scheduledAt
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
